paths:
  # пути до конфигурации и весов модели
  config: "prkt/yolo/yolov4-tiny.cfg"
  weights: "prkt/yolo/yolov4-tiny.weights"
  # путь до видео
  video: /Users/nikita/study/python/park_at/prkt/prkt/tests/frames_3sec
  # http://46.160.254.214:80/mjpg/video.mjpg камера высоко -- пока не видит машины
  # http://185.137.146.14/mjpg/video.mjpg камера в чехии внизу норм качество

model:
  input_size: 608
  confidence_threshold: 0.1
  nms_threshold: 0.4

parking:
  iou_threshold_free: 0.4
  iou_threshold_occupied: 0.6
  free_space_timer: 1

CLASS_IDX: 2
